# Generated by Django 5.2 on 2025-05-03 19:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='products/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
